from __future__ import annotations

import re
import shutil
import subprocess
from pathlib import Path
from typing import Any

from shared.ir import EngineeringIR

EXPORT_FORMATS = {"stl", "png", "3mf", "svg"}
SAFE_IDENTIFIER = re.compile(r"[^A-Za-z0-9_]")


def compile_ir_to_scad(ir: EngineeringIR | dict[str, Any]) -> str:
    payload = ir.model_dump(mode="json") if isinstance(ir, EngineeringIR) else ir
    objects = payload.get("scene", {}).get("objects", [])
    by_id = {item["id"]: item for item in objects}
    referenced = {
        child
        for item in objects
        if item.get("type") in {"operation", "group"}
        for child in item.get("children", [])
    }

    lines = [
        "// Generated by idō. Edit this file or continue prompting.",
        f"// Intent: {payload.get('intent', '')}",
        "$fn = 64;",
        "",
    ]
    for item in objects:
        lines.extend(_module(item, by_id))
        lines.append("")

    roots = [item for item in objects if item["id"] not in referenced]
    lines.append("module ido_scene() {")
    lines.append("  union() {")
    for item in roots:
        if item.get("visible", True):
            lines.append(f"    {_identifier(item['label'])}();")
    lines.extend(["  }", "}", "", "ido_scene();", ""])
    return "\n".join(lines)


def validate_scad_source(source: str) -> list[str]:
    errors: list[str] = []
    if not source.strip():
        errors.append("OpenSCAD source is empty")
    if "```" in source:
        errors.append("OpenSCAD source contains Markdown code fences")
    if source.count("{") != source.count("}"):
        errors.append("OpenSCAD source has unbalanced braces")
    if source.count("(") != source.count(")"):
        errors.append("OpenSCAD source has unbalanced parentheses")
    return errors


def write_scad(source: str, output_dir: str | Path) -> Path:
    errors = validate_scad_source(source)
    if errors:
        raise ValueError("; ".join(errors))
    directory = Path(output_dir).expanduser().resolve()
    directory.mkdir(parents=True, exist_ok=True)
    destination = directory / "ido_current.scad"
    temporary = directory / ".ido_current.scad.tmp"
    temporary.write_text(source, encoding="utf-8")
    if temporary.read_text(encoding="utf-8") != source:
        temporary.unlink(missing_ok=True)
        raise OSError("OpenSCAD file verification failed")
    temporary.replace(destination)
    return destination


def export_with_openscad(
    scad_path: Path,
    formats: list[str],
    *,
    executable: str | None = None,
    timeout: int = 60,
) -> tuple[dict[str, str], list[str]]:
    command_path = executable or shutil.which("openscad")
    if not command_path:
        return {}, ["OpenSCAD CLI was not found"]

    artifacts: dict[str, str] = {}
    errors: list[str] = []
    for requested in formats:
        output_format = requested.lower().strip()
        if output_format not in EXPORT_FORMATS:
            errors.append(f"Unsupported export format: {requested}")
            continue
        output_path = scad_path.with_suffix(f".{output_format}")
        source_path = scad_path
        command = [command_path, "-o", str(output_path), str(source_path)]
        if output_format == "png":
            command = [
                command_path,
                "--imgsize=1200,900",
                "--autocenter",
                "--viewall",
                "-o",
                str(output_path),
                str(source_path),
            ]
        elif output_format == "svg":
            source_path = _projection_source(scad_path)
            command = [command_path, "-o", str(output_path), str(source_path)]
        try:
            completed = subprocess.run(
                command,
                capture_output=True,
                text=True,
                timeout=timeout,
                check=False,
            )
        except (OSError, subprocess.TimeoutExpired) as exc:
            errors.append(f"{output_format}: {exc}")
            continue
        if completed.returncode == 0 and output_path.exists():
            artifacts[output_format] = str(output_path)
        else:
            detail = completed.stderr.strip() or completed.stdout.strip()
            errors.append(f"{output_format}: {detail or 'OpenSCAD export failed'}")
    return artifacts, errors


def _module(item: dict[str, Any], by_id: dict[str, dict[str, Any]]) -> list[str]:
    name = _identifier(item["label"])
    item_type = item.get("type")
    if item_type == "primitive":
        position = item.get("position", {})
        rotation = item.get("rotation", {})
        return [
            f"module {name}() {{",
            f"  translate([{_xyz(position, scale=1000)}])",
            f"  rotate([{_xyz(rotation)}])",
            f"  {_shape(item)}",
            "}",
        ]

    children = [
        _identifier(by_id[child]["label"])
        for child in item.get("children", [])
        if child in by_id
    ]
    operation = item.get("operation", "union") if item_type == "operation" else "union"
    lines = [f"module {name}() {{", f"  {operation}() {{"]
    lines.extend(f"    {child}();" for child in children)
    lines.extend(["  }", "}"])
    return lines


def _shape(item: dict[str, Any]) -> str:
    dimensions = item.get("dimensions", {})
    shape = item.get("shape")
    if shape in {"box", "prism"}:
        width = _length(dimensions.get("width", 1))
        depth = _length(dimensions.get("depth", 1))
        height = _length(dimensions.get("height", 1))
        if shape == "box":
            return f"cube([{width}, {depth}, {height}], center=true);"
        return (
            f"linear_extrude(height={depth}, center=true) "
            f"polygon(points=[[-{width}/2, 0], [{width}/2, 0], [0, {height}]]);"
        )
    radius = _length(dimensions.get("radius", 1))
    if shape == "sphere":
        return f"sphere(r={radius});"
    height = _length(dimensions.get("height", 1))
    if shape == "cone":
        return f"cylinder(h={height}, r1={radius}, r2=0, center=true);"
    return f"cylinder(h={height}, r={radius}, center=true);"


def _projection_source(scad_path: Path) -> Path:
    projection = scad_path.with_name("ido_current_projection.scad")
    projection.write_text(
        f"use <{scad_path.as_posix()}>;\n\nprojection(cut=false) ido_scene();\n",
        encoding="utf-8",
    )
    return projection


def _identifier(value: str) -> str:
    cleaned = SAFE_IDENTIFIER.sub("_", value)
    return cleaned if cleaned[:1].isalpha() or cleaned.startswith("_") else f"obj_{cleaned}"


def _xyz(value: dict[str, Any], *, scale: float = 1) -> str:
    return ", ".join(
        _number(float(value.get(axis, 0)) * scale) for axis in ("x", "y", "z")
    )


def _number(value: Any) -> str:
    return f"{float(value):.6g}"


def _length(value: Any) -> str:
    return _number(float(value) * 1000)
